---
openapi: 3.0.0
info:
  title: Mission Stickers API
  version: "0.0.1"
  description:
    This document describes LINE Mission Stickers API.

servers:
  - url: "https://api.line.me"

security:
  - Bearer: []

tags:
  - name: shop

paths:
  "/shop/v3/mission":
    post:
      externalDocs:
        url: https://developers.line.biz/en/reference/partner-docs/#send-mission-stickers-v3
      tags:
        - shop
      operationId: missionStickerV3
      description: Sends a mission sticker.
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/MissionStickerRequest"
        required: true
      responses:
        "200":
          description: Returns status code 200 and an empty response body.
          # TODO content-type?

components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      description: Channel access token

  schemas:
    MissionStickerRequest:
      externalDocs:
        url: https://developers.line.biz/en/reference/partner-docs/#send-mission-stickers-v3
      description: Send mission stickers (v3)
      required:
        - to
        - productId
        - productType
        - sendPresentMessage
      type: object
      properties:
        to:
          type: string
          description: Destination user ID
        productId:
          type: string
          description: Package ID for a set of stickers
        productType:
          type: string
          description: "`STICKER`"
          example: STICKER
        sendPresentMessage:
          type: boolean
          description: "`false`"
          example: false
