name: Basic CI

on:
  push:
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Use Node.js
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        cache: 'npm'
    - run: npm ci
    - run: npm run validate:all
    - run: npm run validate:request-suffix
    - run: npm run validate:inheritance

  format-diff:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        cache: 'npm'
    - run: npm ci
    - run: npm run format
    - name: Check there is no diff (Run ./tools/reformat.mjs if there is a diff)
      run: git diff --exit-code

  property-should-be-camelcase:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        # ensures origin/main is available for git show
        fetch-depth: 0
    - name: Use Node.js
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        cache: 'npm'
    - run: npm ci
    - run: node tools/validate-property-camelcase.mjs

  pinact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Run pinact
        uses: suzuki-shunsuke/pinact-action@3132770ecce73073bcd618342c7f4092ed2f994c # v3.0.0
        with:
          skip_push: "true"
