name: Basic CI

on:
  push:
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Use Node.js
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        cache: 'npm'
    - run: npm install -g @stoplight/spectral-cli
    - run: npm install .
    - run: npx zx ./tools/validate-all.mjs
    - run: npx zx ./tools/validate-request-suffix.mjs
    - run: npx zx ./tools/validate-inheritance.mjs

  generate-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Use Node.js
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        cache: 'npm'
    - run: npm install -g @openapitools/openapi-generator-cli
    - run: openapi-generator-cli version-manager set 7.0.1
    - run: sed -i -e 's/openapi-generator/openapi-generator-cli/g' ./tools/generate-test.mjs
    - name: actions/setup-java@v3 (JDK 17)
      uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
      with:
        distribution: 'temurin'
        java-version: 17
        architecture: x64
    - run: npx zx ./tools/generate-test.mjs

  format-diff:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        cache: 'npm'
    - run: npx zx ./tools/reformat.mjs
    - name: Check there is no diff (Run ./tools/reformat.mjs if there is a diff)
      run: git diff --exit-code

  property-should-be-camelcase:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        # ensures origin/main is available for git show
        fetch-depth: 0
    - name: Use Node.js
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        cache: 'npm'
    - run: npm install
    - run: node tools/validate-property-camelcase.mjs

  pinact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Run pinact
        uses: suzuki-shunsuke/pinact-action@896d595f299e71d65b9d28349d6956abe144390a # v3.0.0
        with:
          skip_push: "true"
