name: Warn PR from forked repository

on:
  # Intentional: forked repository doesn't have write permission to the base repository.
  pull_request_target:
    types: [opened]

jobs:
  comment-on-forked-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Add a comment if PR is from a fork
        if: ${{ github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name }}
        run: |
          PR_AUTHOR=${{ github.event.pull_request.user.login }}
          COMMENT=":warning: Attention @$PR_AUTHOR!
            Thank you for your interest in contributing to this repository!

            This repository primarily exists to convert publicly available LINE APIs into OpenAPI YAML, making it easier for developers to access the features.
            Our employees mainly update the schema based on the latest features and changes in our APIs.
            
            Therefore, it is not intended for open contributions by editing files in this repository, from outside contributors.

            Please start by creating an issue and discussing it there. You may close this pull request and create an issue instead.

            ==
            If you are an employee participating in this organization, please push branches directly to this repository to create PR, instead of using a forked repository.
          "
          
          gh pr comment ${{ github.event.pull_request.number }} --body "$COMMENT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
